# Generated by Django 4.2.2 on 2023-06-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_tags_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='名無し', max_length=255, verbose_name='名前'),
        ),
    ]
