# Generated by Django 4.2.2 on 2023-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_book_staff_rented_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='rented_books',
            field=models.ManyToManyField(blank=True, null=True, to='myapp2.book', verbose_name='借りている本'),
        ),
    ]
